//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMPrac2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSTOMER
    {
        public int Id { get; set; }
        public string CUST_CODE { get; set; }
        public string COST_NAME { get; set; }
        public string COST_CITY { get; set; }
        public string WORKING_AREA { get; set; }
        public string COST_COUSTRY { get; set; }
        public int GRADE { get; set; }
        public decimal OPENING_AMT { get; set; }
        public decimal RECEIVE_AMT { get; set; }
        public decimal PAYMENT_ATM { get; set; }
        public decimal OUSTANDIG_ATM { get; set; }
        public string PHONE_NO { get; set; }
        public string AGENT_CODE { get; set; }
        public int AGENTSAGENT_CODE { get; set; }
        public int ORDERSId { get; set; }
    
        public virtual AGENTS AGENTS { get; set; }
        public virtual ORDERS ORDERS { get; set; }
    }
}
